import {
  AppleIcon,
  BrainIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  ChartNoAxesCombinedIcon,
  CompassIcon,
  HeartPulseIcon,
  LayoutDashboardIcon,
  LayoutGridIcon,
  ListChecksIcon,
  SettingsIcon,
  SmileIcon,
  SparklesIcon,
  TargetIcon,
  TimerIcon,
  WalletIcon,
} from "lucide-react";

export const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutGridIcon },
  { href: "/today", label: "Today", icon: LayoutDashboardIcon },
  { href: "/calendar", label: "Calendar", icon: CalendarDaysIcon },
  { href: "/goals", label: "Goals", icon: TargetIcon },
  { href: "/habits", label: "Habits", icon: ListChecksIcon },
  { href: "/mood", label: "Mood", icon: SmileIcon },
  { href: "/nutrition", label: "Nutrition", icon: AppleIcon },
  { href: "/health", label: "Health", icon: HeartPulseIcon },
  { href: "/finance", label: "Finance", icon: WalletIcon },
  { href: "/discover", label: "Discover", icon: CompassIcon },
  { href: "/memory", label: "Memory", icon: BrainIcon },
  { href: "/analytics", label: "Analytics", icon: ChartNoAxesCombinedIcon },
  { href: "/focus", label: "Focus", icon: TimerIcon },
  { href: "/stats", label: "Stats", icon: CalendarClockIcon },
  { href: "/chat", label: "Assistant", icon: SparklesIcon },
  { href: "/settings", label: "Settings", icon: SettingsIcon },
] as const;
