import type { ActivityCategory } from "./geoapify-client";

export const ACTIVITY_CATEGORY_LABEL: Record<ActivityCategory, string> = {
  restaurants: "Restaurants",
  coffee: "Coffee",
  desserts: "Desserts",
  bars: "Bars & pubs",
  nightlife: "Nightlife",
  museums: "Museums",
  galleries: "Galleries & culture",
  parks: "Parks & forests",
  lakes_beaches: "Lakes & beaches",
  attractions: "Attractions",
  active_sports: "Sports & fields",
  gyms: "Gyms & fitness",
  pools: "Swimming pools",
  golf: "Golf",
  shopping: "Shopping",
  bookstores: "Bookstores",
  libraries: "Libraries",
  coworking: "Coworking",
  cinema: "Cinema",
  gaming: "Bowling & games",
  zoos_aquariums: "Zoos & aquariums",
  family: "Family & kids",
  learning: "Learning",
  relax: "Relax & spa",
};

export const ACTIVITY_CATEGORY_ICON: Record<ActivityCategory, string> = {
  restaurants: "🍽️",
  coffee: "☕",
  desserts: "🍰",
  bars: "🍸",
  nightlife: "🌃",
  museums: "🏛️",
  galleries: "🎨",
  parks: "🌳",
  lakes_beaches: "🏖️",
  attractions: "🗼",
  active_sports: "🏟️",
  gyms: "💪",
  pools: "🏊",
  golf: "⛳",
  shopping: "🛍️",
  bookstores: "📖",
  libraries: "📚",
  coworking: "💻",
  cinema: "🎬",
  gaming: "🎳",
  zoos_aquariums: "🐠",
  family: "👨‍👩‍👧",
  learning: "🎓",
  relax: "🧘",
};
